### ISSUE TITLE
"Using $this when not in object context" Laravel Dadata

### ISSUE THREAD

**Issue by palachX** [sushi-market/laravel-dadata#1]
Добрый день установил плагин с игнор версией, а также пробовал устанавливать версию от ребят из сушимаркета (https://github.com/sushi-market/laravel-dadata) но всё равно выбивает эту ошибку при запросе:

exception: "Error"
file: "/home/cotit/dev3/vendor/movemoveapp/laravel-dadata/src/DaDataAddress.php"
line: 59
message: "Using $this when not in object context"

В чём проблема?

**Comment by denis660** [comment]
Есть пример, как получилась эта ошибка ?  При тестовых запросах все работает
Метод который вызвали, какие данные передали, лучше прям код прислать с примером

**Comment by palachX** [comment]
> Есть пример, как получилась эта ошибка ? При тестовых запросах все работает Метод который вызвали, какие данные передали, лучше прям код прислать с примером


К сожалению кода не осталось но использовал так как и описано в примерах
 
$dadata = DaDataAddress::prompt('мск сухонска 11/-89');

Я поставил https://github.com/hflabs/dadata-php 
И написал свой сервис, поэтому всё нормуль)

Но ошибка скорее всего была в том что не было создано создано класса DaDataAddress.
Потому что даже иногда сейчас в некоторых случаях мне приходится создавать класс пример:
$daDataService = new DadataService();  т.к. внутри данного класса без его создания не может использовать $this, либо переделывать всё в статические методы и переменные.

**Comment by denis660** [comment]
Проверили, ошибок тут не нашли, проблема была в корректном вызове методов
